import React, { Suspense } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Loading from "./loading";

// Import Inter font from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap", // Ensures faster font rendering
});

export const metadata: Metadata = {
  title: "tutorFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="antialiased bg-gray-50">
        <Suspense fallback={<Loading />}>
          {children}
          <footer className="flex gap-2.5 items-center w-full text-center text-black min-h-[96px] max-md:max-w-full">
          <div className="flex overflow-hidden relative flex-wrap flex-1 shrink gap-4 items-start self-stretch my-auto w-full border-t basis-0 bg-zinc-100 border-zinc-300 min-h-[96px] min-w-[240px] max-md:max-w-full">
            <div className="absolute z-0 text-xs leading-8 bottom-[21px] h-[31px] left-[650px] w-[263px]">
              Copyright © 2024 tutorFlow. All rights reserved.
            </div>
            <div className="absolute z-0 h-8 text-base font-bold tracking-tight leading-5 left-[620px] top-[23px] w-[327px]">
              <span className="text-slate-600">tutor</span>
              <span className="text-slate-300">Flow</span>
            </div>
          </div>
        </footer>
        </Suspense>
      </body>
    </html>
  );
}
